-- ============================================================================
-- BGTS-OS database schema — migration 0001  (v2 — corrected ID type, see note)
-- ============================================================================
-- Everything for this app lives in its own Postgres schema, "bgts_os", so it
-- can share the same Supabase project as your existing BGTS website without
-- any risk of table-name collisions with whatever that site already uses in
-- "public". Run this file (and 0002_functions.sql, 0003_rls.sql after it) in
-- the Supabase SQL Editor of your EXISTING project — nothing here creates a
-- new project or touches any table outside this schema.
--
-- CORRECTION FROM THE FIRST VERSION OF THIS FILE: every table below used a
-- `uuid` primary key generated by the database. That's wrong for this app —
-- the existing screens generate their own ids client-side via uid() in
-- src/logic.js (e.g. "lr1a2b3c4d"), and every single one of the ~20 screens
-- calls that function directly when creating a record. Keeping the database
-- in charge of id generation would mean either rewriting every create-action
-- in every screen (exactly what you said not to do) or living with two
-- different, disconnected id schemes. So every id column here is `text`,
-- supplied by the app exactly as it is today — the database's job is to
-- store and constrain those ids (uniqueness, foreign keys), not generate
-- new ones. If you already ran the first version of this file, drop the
-- schema and re-run this corrected version — see the note at the very top
-- of the SQL Editor instructions you were given.
--
-- This schema is a 1:1 mapping of the app's current data model as it exists
-- today in src/logic.js's blankDB()/blankLR()/blankInquiry() and every screen
-- that creates records — no invented fields, no invented "Quote" entity (the
-- app has none), no renamed statuses. Every enum CHECK constraint below uses
-- the exact string values already used in the app so existing UI code needs
-- no relabeling.
-- ============================================================================

create schema if not exists bgts_os;
set search_path = bgts_os, public;

-- A handful of child-table rows have no id in the app's own data model at all
-- (LR goods rows, LR expense lines, contract rate lines, legacy billing-
-- backup lines/bills — see blankLR().goods, contract.rates, etc. in
-- src/logic.js, none of which carry an id field). Those get a
-- database-generated surrogate key (still stored as text, for consistency
-- with every other id in this schema) since nothing in the app needs to
-- reference them individually. gen_random_uuid() is built into Postgres core
-- on 13+, which is what every current Supabase project runs — no extension
-- needed.

-- ----------------------------------------------------------------------------
-- Company profile (singleton) — src/logic.js blankDB().company, edited in
-- SettingsScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.company_settings (
  id          smallint primary key default 1 check (id = 1), -- enforce single row
  name        text not null default '',
  addr        text not null default '',
  gstin       text not null default '',
  phone       text not null default '',
  email       text not null default '',
  lr_prefix   text not null default '',
  updated_at  timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- Sequential numbering (LR-0001, INV-0001, etc.) — src/logic.js db.seq
-- Replaces client-side counters with atomic DB counters (see 0002_functions.sql
-- for the next_counter() function used to increment these safely under
-- concurrent writes). This is unrelated to the row-id correction above —
-- these are the human-readable document numbers, not primary keys.
-- ----------------------------------------------------------------------------
create table bgts_os.counters (
  name   text primary key,     -- 'lr' | 'inv' | 'bk' | 'lhc' | 'inq' | 'mr'
  value  bigint not null default 0
);
insert into bgts_os.counters (name, value) values
  ('lr', 0), ('inv', 0), ('bk', 0), ('lhc', 0), ('inq', 0), ('mr', 0)
on conflict (name) do nothing;

-- ----------------------------------------------------------------------------
-- Master data — Masters screen tabs
-- ----------------------------------------------------------------------------
create table bgts_os.branches (
  id           text primary key,
  name         text not null,
  entity_name  text not null default '',
  gstin        text not null default '',
  addr         text not null default '',
  lr_prefix    text not null default '',
  phone        text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table bgts_os.clients (
  id           text primary key,
  name         text not null,
  gstin        text not null default '',
  phone        text not null default '',
  email        text not null default '',
  credit_days  integer not null default 30,
  addr         text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_clients_name on bgts_os.clients (lower(name));

create table bgts_os.drivers (
  id           text primary key,
  name         text not null,
  phone        text not null default '',
  lic_no       text not null default '',
  lic_expiry   date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table bgts_os.vendors (
  id           text primary key,
  name         text not null,
  phone        text not null default '',
  city         text not null default '',
  rating       text not null default 'B' check (rating in ('A', 'B', 'C')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table bgts_os.vehicles (
  id           text primary key,
  reg_no       text not null unique,
  make         text not null default '',
  type         text not null default '',
  owned        boolean not null default true,
  gvw          text not null default '',
  driver_id    text references bgts_os.drivers (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_vehicles_driver on bgts_os.vehicles (driver_id);

create table bgts_os.routes (
  id           text primary key,
  origin       text not null,
  destination  text not null,
  km           numeric,
  created_at   timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- Contracts / Tenders (rate engine source) — ContractsScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.contracts (
  id           text primary key,
  type         text not null check (type in ('Tender', 'Annual Contract', 'Company Contract')),
  client_id    text references bgts_os.clients (id) on delete set null,
  ref          text not null default '',
  valid_from   date,
  valid_to     date,
  emd          numeric,
  bg_expiry    date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_contracts_client on bgts_os.contracts (client_id);

-- contract.rates[] items have no id in the app's data model — surrogate key.
create table bgts_os.contract_rates (
  id            text primary key default gen_random_uuid()::text,
  contract_id   text not null references bgts_os.contracts (id) on delete cascade,
  origin        text not null,
  destination   text not null,
  vehicle_type  text not null default '',
  rate          numeric not null default 0
);
create index idx_contract_rates_lookup on bgts_os.contract_rates (contract_id, origin, destination, vehicle_type);

-- ----------------------------------------------------------------------------
-- Inquiries — InquiriesScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.inquiries (
  id                    text primary key,
  inq_no                text not null unique,
  status                text not null default 'OPEN' check (status in ('OPEN', 'CONFIRMED', 'CONVERTED', 'LOST')),
  date                  date not null default current_date,
  branch_id             text references bgts_os.branches (id) on delete set null,
  client_id             text references bgts_os.clients (id) on delete set null,
  party_name            text not null default '',
  contact               text not null default '',
  from_place            text not null default '',
  to_place              text not null default '',
  vehicle_type          text not null default '',
  cargo                 text not null default '',
  weight_mt             numeric,
  expected_date         date,
  rate_quoted           numeric,
  ownership_pref        text not null default '' check (ownership_pref in ('', 'Owned', 'Hired')),
  notes                 text not null default '',
  assign_type           text not null default '' check (assign_type in ('', 'Owned', 'Hired')),
  assigned_vehicle_id   text references bgts_os.vehicles (id) on delete set null,
  assigned_vendor_id    text references bgts_os.vendors (id) on delete set null,
  assigned_truck_no     text not null default '',
  booking_id            text, -- FK added after bookings table exists (see below)
  lr_id                 text, -- FK added after lrs table exists (see below)
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index idx_inquiries_status on bgts_os.inquiries (status);
create index idx_inquiries_client on bgts_os.inquiries (client_id);
create index idx_inquiries_date on bgts_os.inquiries (date desc);

-- ----------------------------------------------------------------------------
-- Bookings — BookingsScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.bookings (
  id                 text primary key,
  bk_no              text not null unique,
  date               date not null default current_date,
  branch_id          text references bgts_os.branches (id) on delete set null,
  client_id          text references bgts_os.clients (id) on delete set null,
  origin             text not null default '',
  destination        text not null default '',
  mode               text not null default 'Road' check (mode in ('Road', 'Rail', 'Air')),
  vehicle_type       text not null default '',
  cargo              text not null default '',
  weight_mt          numeric,
  freight            numeric not null default 0,
  rate_source        text not null default '',
  assign_type        text not null default '' check (assign_type in ('', 'Owned', 'Hired')),
  vehicle_id         text references bgts_os.vehicles (id) on delete set null,
  hired_vendor_id    text references bgts_os.vendors (id) on delete set null,
  hired_vehicle_no   text not null default '',
  hire_cost          numeric,
  driver_id          text references bgts_os.drivers (id) on delete set null,
  status             text not null default 'Booked' check (status in
                       ('Booked', 'Vehicle Assigned', 'In Transit', 'Delivered', 'Invoiced', 'Paid')),
  lr_no              text not null default '',
  eway_bill          text not null default '',
  pod_received       boolean not null default false,
  invoice_id         text, -- FK added after invoices table exists (see below)
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index idx_bookings_status on bgts_os.bookings (status);
create index idx_bookings_client on bgts_os.bookings (client_id);
create index idx_bookings_date on bgts_os.bookings (date desc);

alter table bgts_os.inquiries
  add constraint fk_inquiries_booking foreign key (booking_id) references bgts_os.bookings (id) on delete set null;

-- ----------------------------------------------------------------------------
-- LR / Consignment Notes — LRFormScreen.js / LRScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.lrs (
  id                text primary key,
  booking_id        text references bgts_os.bookings (id) on delete set null,
  lr_type           text not null default 'ORIGINAL' check (lr_type in ('ORIGINAL', 'DUMMY')),
  truck_no          text not null default '',
  lr_no             text not null unique,
  date              date not null default current_date,
  booking_branch    text not null default '',
  from_place        text not null default '',
  to_place          text not null default '',
  to_branch         text not null default '',
  invoice_no        text not null default '',
  inv_amount        numeric,
  invoice_date      date,
  eway_bill_no      text not null default '',
  eway_bill_date    date,
  eway_ex_date      date,
  po_date           date,
  packing           text not null default '',
  lorry_type        text not null default '',
  private_mark      text not null default '',
  lr_mode           text not null default '' check (lr_mode in ('', 'Door Delivery', 'Godown Delivery', 'Direct Delivery')),
  delivery_address  text not null default '',
  billing_party     text not null default '' check (billing_party in ('', 'Consignor', 'Consignee', 'Third Party')),
  gst_paid_by       text not null default '' check (gst_paid_by in ('', 'Consignor', 'Consignee', 'Transporter')),
  gst_slab          text not null default '' check (gst_slab in ('', 'Exempt (RCM)', '0%', '5%', '12%', '18%')),
  insurance         text not null default '',
  pay_terms         text not null default '' check (pay_terms in ('', 'PAID', 'TO PAY', 'TO BE BILLED')),
  agent             text not null default '',
  billed_at         text not null default '',
  a_weight          numeric,
  c_weight          numeric,
  remark            text not null default '',
  employee          text not null default '',
  driver_no         text not null default '',
  igst_pct          numeric not null default 0,
  cgst_pct          numeric not null default 0,
  sgst_pct          numeric not null default 0,
  sub_total         numeric not null default 0,
  igst_amt          numeric not null default 0,
  cgst_amt          numeric not null default 0,
  sgst_amt          numeric not null default 0,
  gross             numeric not null default 0,
  pod               boolean not null default false,
  pod_file_uri      text,
  pod_receiver      text,
  pod_date          date,
  pod_remarks       text,
  ownership         text not null default 'Owned' check (ownership in ('Owned', 'Hired')),
  vehicle_id        text references bgts_os.vehicles (id) on delete set null,
  branch_id         text references bgts_os.branches (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index idx_lrs_booking on bgts_os.lrs (booking_id);
create index idx_lrs_date on bgts_os.lrs (date desc);
create index idx_lrs_branch on bgts_os.lrs (branch_id);

alter table bgts_os.inquiries
  add constraint fk_inquiries_lr foreign key (lr_id) references bgts_os.lrs (id) on delete set null;

-- LR parties: consignor / consignee / billing-to (3 fixed roles per LR).
-- Requirement #9/#10 — one child row per role instead of duplicating 5 columns
-- x3 on the parent table. No id in the app's model — surrogate key.
create table bgts_os.lr_parties (
  id       text primary key default gen_random_uuid()::text,
  lr_id    text not null references bgts_os.lrs (id) on delete cascade,
  role     text not null check (role in ('consignor', 'consignee', 'billing_to')),
  name     text not null default '',
  city     text not null default '',
  contact  text not null default '',
  pan      text not null default '',
  gst      text not null default '',
  unique (lr_id, role)
);

-- LR goods rows — requirement #10: proper 1:many child table, never a
-- comma-separated text blob. No id in the app's model — surrogate key.
create table bgts_os.lr_goods (
  id          text primary key default gen_random_uuid()::text,
  lr_id       text not null references bgts_os.lrs (id) on delete cascade,
  sort_order  integer not null default 0,
  description text not null default '',
  pkg_type    text not null default '',
  pcs         numeric,
  actual_wt   numeric,
  charged_wt  numeric,
  length_cm   numeric,
  width_cm    numeric,
  height_cm   numeric
);
create index idx_lr_goods_lr on bgts_os.lr_goods (lr_id, sort_order);

-- LR charges — requirement #11: one row per LR (1:1), individual columns per
-- charge type so nothing is flattened into a single opaque total.
create table bgts_os.lr_charges (
  lr_id         text primary key references bgts_os.lrs (id) on delete cascade,
  above_pct     numeric not null default 0,
  above_ch      numeric not null default 0,
  below_pct     numeric not null default 0,
  below_ch      numeric not null default 0,
  rate          numeric not null default 0,
  rate_ch       numeric not null default 0,
  freight       numeric not null default 0,
  surcharge     numeric not null default 0,
  local_cartage numeric not null default 0,
  last_mile     numeric not null default 0,
  fov           numeric not null default 0,
  loading       numeric not null default 0,
  unloading     numeric not null default 0,
  handling      numeric not null default 0,
  gc            numeric not null default 0,
  other         numeric not null default 0,
  eway_ch       numeric not null default 0,
  aoc           numeric not null default 0
);

-- LR expense lines — the repeatable "LR Expenses" rows entered on the LR form
-- (account/amount/remarks), the *source* rows that get posted into
-- acct_expenses on save. No id in the app's model — surrogate key.
create table bgts_os.lr_expense_lines (
  id       text primary key default gen_random_uuid()::text,
  lr_id    text not null references bgts_os.lrs (id) on delete cascade,
  account  text not null default '',
  amount   numeric not null default 0,
  remarks  text not null default ''
);

-- Hire details for Hired-ownership LRs — 1:1 with the LR.
create table bgts_os.lr_hire (
  lr_id      text primary key references bgts_os.lrs (id) on delete cascade,
  vendor_id  text references bgts_os.vendors (id) on delete set null,
  amount     numeric not null default 0,
  advance    numeric not null default 0
);

-- lr.hire.payments[] items DO carry an app-generated id (uid('hp')).
create table bgts_os.lr_hire_payments (
  id       text primary key,
  lr_id    text not null references bgts_os.lrs (id) on delete cascade,
  date     date not null default current_date,
  amount   numeric not null default 0,
  mode     text not null default '' check (mode in ('', 'NEFT/RTGS', 'UPI', 'Cash', 'Cheque')),
  ref      text not null default '',
  created_at timestamptz not null default now()
);
create index idx_lr_hire_payments_lr on bgts_os.lr_hire_payments (lr_id);

-- ----------------------------------------------------------------------------
-- Fleet / vehicle expenses — FleetScreen.js, also linked from LR trip-expense
-- flow (LRScreen.js "+ Trip Exp")
-- ----------------------------------------------------------------------------
create table bgts_os.expenses (
  id          text primary key,
  vehicle_id  text references bgts_os.vehicles (id) on delete set null,
  lr_id       text references bgts_os.lrs (id) on delete set null,
  date        date not null default current_date,
  category    text not null default '',
  amount      numeric not null default 0,
  litres      numeric,
  notes       text not null default '',
  created_at  timestamptz not null default now()
);
create index idx_expenses_vehicle on bgts_os.expenses (vehicle_id);
create index idx_expenses_lr on bgts_os.expenses (lr_id);

-- lr.tripExpenses[] summary rows reference expenses.id but have no id of
-- their own in the app's model — surrogate key.
create table bgts_os.lr_trip_expenses (
  id          text primary key default gen_random_uuid()::text,
  lr_id       text not null references bgts_os.lrs (id) on delete cascade,
  expense_id  text not null references bgts_os.expenses (id) on delete cascade,
  date        date not null default current_date,
  category    text not null default '',
  amount      numeric not null default 0
);
create index idx_lr_trip_expenses_lr on bgts_os.lr_trip_expenses (lr_id);

-- ----------------------------------------------------------------------------
-- Renewals / compliance calendar — RenewalsScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.renewals (
  id          text primary key,
  vehicle_id  text not null references bgts_os.vehicles (id) on delete cascade,
  doc_type    text not null check (doc_type in
                ('Insurance', 'Permit (National)', 'Permit (State)', 'Fitness', 'PUC',
                 'Road Tax', 'RC', 'Goods Carriage Permit', 'Other')),
  ref         text not null default '',
  expiry      date,
  created_at  timestamptz not null default now()
);
create index idx_renewals_vehicle on bgts_os.renewals (vehicle_id);
create index idx_renewals_expiry on bgts_os.renewals (expiry);

-- ----------------------------------------------------------------------------
-- Invoices, invoice-bookings junction, payments — AccountingScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.invoices (
  id          text primary key,
  inv_no      text not null unique,
  date        date not null default current_date,
  branch_id   text references bgts_os.branches (id) on delete set null,
  client_id   text references bgts_os.clients (id) on delete set null,
  amount      numeric not null default 0, -- taxable amount
  gst_pct     numeric not null default 0,
  total       numeric not null default 0,
  due_date    date,
  notes       text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index idx_invoices_client on bgts_os.invoices (client_id);
create index idx_invoices_date on bgts_os.invoices (date desc);

alter table bgts_os.bookings
  add constraint fk_bookings_invoice foreign key (invoice_id) references bgts_os.invoices (id) on delete set null;

-- One invoice can cover multiple bookings (invoices.bookingIds[] in the app) —
-- junction table instead of an array column, per the "normalized, not one
-- big blob" requirement.
create table bgts_os.invoice_bookings (
  invoice_id  text not null references bgts_os.invoices (id) on delete cascade,
  booking_id  text not null references bgts_os.bookings (id) on delete cascade,
  primary key (invoice_id, booking_id)
);

create table bgts_os.payments (
  id            text primary key,
  mr_no         text not null unique,
  invoice_id    text not null references bgts_os.invoices (id) on delete cascade,
  date          date not null default current_date,
  amount        numeric not null default 0,
  mode          text not null default '' check (mode in ('', 'NEFT/RTGS', 'UPI', 'Cheque', 'Cash', 'Other')),
  ref           text not null default '',
  bank_txn_id   text, -- FK added after bank_txns table exists (see below)
  created_at    timestamptz not null default now()
);
create index idx_payments_invoice on bgts_os.payments (invoice_id);

-- ----------------------------------------------------------------------------
-- Bank reconciliation — BankingScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.bank_txns (
  id           text primary key,
  date         date not null default current_date,
  narration    text not null default '',
  ref          text not null default '',
  amount       numeric not null default 0,
  status       text not null default 'UNMATCHED' check (status in ('UNMATCHED', 'MATCHED', 'IGNORED')),
  dedupe_key   text not null unique,
  payment_id   text references bgts_os.payments (id) on delete set null,
  created_at   timestamptz not null default now()
);
create index idx_bank_txns_status on bgts_os.bank_txns (status);

alter table bgts_os.payments
  add constraint fk_payments_bank_txn foreign key (bank_txn_id) references bgts_os.bank_txns (id) on delete set null;

-- ----------------------------------------------------------------------------
-- Lorry Hire Contracts (market-truck hire, independent of the LR/booking
-- chain) — LHCScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.lhcs (
  id            text primary key,
  lhc_no        text not null unique,
  date          date not null default current_date,
  vendor_id     text references bgts_os.vendors (id) on delete set null,
  truck_no      text not null default '',
  driver_name   text not null default '',
  driver_phone  text not null default '',
  from_place    text not null default '',
  to_place      text not null default '',
  lr_nos        text not null default '', -- free text in the app today, not a real FK — preserved as-is
  lorry_hire    numeric not null default 0,
  advance       numeric not null default 0,
  deductions    numeric not null default 0,
  tds_pct       numeric not null default 0 check (tds_pct in (0, 1, 2, 20)),
  tds_amt       numeric not null default 0,
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- lhc.payments[] items DO carry an app-generated id (uid('lp')).
create table bgts_os.lhc_payments (
  id       text primary key,
  lhc_id   text not null references bgts_os.lhcs (id) on delete cascade,
  date     date not null default current_date,
  amount   numeric not null default 0,
  mode     text not null default '' check (mode in ('', 'NEFT/RTGS', 'UPI', 'Cash', 'Cheque')),
  ref      text not null default '',
  created_at timestamptz not null default now()
);
create index idx_lhc_payments_lhc on bgts_os.lhc_payments (lhc_id);

-- ----------------------------------------------------------------------------
-- Driver advances — AdvancesScreen.js
-- ----------------------------------------------------------------------------
create table bgts_os.advances (
  id               text primary key,
  driver_id        text not null references bgts_os.drivers (id) on delete cascade,
  date             date not null default current_date,
  amount           numeric not null default 0,
  purpose          text not null default '',
  settled_amount   numeric not null default 0,
  settled_at       date,
  created_at       timestamptz not null default now()
);
create index idx_advances_driver on bgts_os.advances (driver_id);

-- ----------------------------------------------------------------------------
-- Business/accounting expense ledger — AccountingScreen.js "Business
-- Expenses", also auto-posted from LR expense lines and hire advances/
-- payments. id here IS the app-generated id, and for the two auto-posted
-- kinds is deterministic ('hadv_<lrId>', 'hpay_<paymentId>') exactly as the
-- app already builds it — that determinism is what makes re-saving an LR or
-- hire payment replace its own posting instead of duplicating it, since the
-- same id simply gets upserted.
-- ----------------------------------------------------------------------------
create table bgts_os.acct_expenses (
  id            text primary key,
  lr_id         text references bgts_os.lrs (id) on delete set null,
  branch_id     text references bgts_os.branches (id) on delete set null,
  date          date not null default current_date,
  account       text not null check (account in (
                  'Fuel Expense', 'Toll & FASTag', 'Driver Salaries & Bhatta',
                  'Vehicle Repairs & Maintenance', 'Tyres & Spares', 'Vehicle Insurance & Permits',
                  'Loading & Unloading Charges', 'Hired Vehicle / Subcontractor', 'Warehouse Rent',
                  'Office & Admin', 'Telephone & Internet', 'Bank Fees and Charges',
                  'E-Way Bill / Compliance', 'Other Expenses')),
  amount        numeric not null default 0,
  paid_through  text not null default '' check (paid_through in
                  ('', 'Bank — Current A/c', 'Petty Cash', 'UPI', 'Credit (payable)')),
  vendor        text not null default '',
  ref           text not null default '',
  notes         text not null default '',
  src           text not null default 'manual' check (src in ('manual', 'lr', 'hire')),
  created_at    timestamptz not null default now()
);
create index idx_acct_expenses_lr on bgts_os.acct_expenses (lr_id);
create index idx_acct_expenses_branch on bgts_os.acct_expenses (branch_id);
create index idx_acct_expenses_date on bgts_os.acct_expenses (date desc);

-- ----------------------------------------------------------------------------
-- Legacy Invoice Backup / Billing Register archive — BackupScreen.js
-- (read-only historical archive, matched to invoices only by string parsing
-- in the existing app — preserved as its own standalone structure). Neither
-- bills nor their lines carry an id in the app's model — surrogate keys.
-- ----------------------------------------------------------------------------
create table bgts_os.billing_backup_bills (
  id          text primary key default gen_random_uuid()::text,
  bill_no     text not null,
  client_name text not null default '',
  bill_date   date,
  total       numeric not null default 0,
  created_at  timestamptz not null default now()
);

create table bgts_os.billing_backup_lines (
  id        text primary key default gen_random_uuid()::text,
  bill_id   text not null references bgts_os.billing_backup_bills (id) on delete cascade,
  lr_no     text not null,
  amount    numeric not null default 0
);
create index idx_billing_backup_lines_bill on bgts_os.billing_backup_lines (bill_id);

-- ----------------------------------------------------------------------------
-- Status / audit history — requirement #18. Generic table covering every
-- entity that has a status field (inquiries, bookings, lrs where relevant).
-- Written by the sync layer, not by the app directly, so a generated id here
-- is fine.
-- ----------------------------------------------------------------------------
create table bgts_os.status_history (
  id               text primary key default gen_random_uuid()::text,
  entity_type      text not null check (entity_type in ('inquiry', 'booking', 'invoice', 'bank_txn')),
  entity_id        text not null,
  previous_status  text,
  new_status       text not null,
  changed_by       uuid references auth.users (id), -- real Supabase Auth user id — unrelated to the app-id correction above
  changed_at       timestamptz not null default now(),
  comment          text
);
create index idx_status_history_entity on bgts_os.status_history (entity_type, entity_id, changed_at desc);

-- ----------------------------------------------------------------------------
-- App users / profile — created because this rollout adds Supabase Auth
-- (email/password) as the minimum viable login gate; every authenticated
-- user is currently treated as one shared company account (see 0003_rls.sql),
-- not per-record ownership — the app itself has no roles/permissions model
-- today, so this profile table exists mainly to give status_history.changed_by
-- a friendly name to show, and as the place to add real roles later. id is a
-- real Supabase Auth user id (uuid) — unrelated to the app-id correction above.
-- ----------------------------------------------------------------------------
create table bgts_os.app_users (
  id          uuid primary key references auth.users (id) on delete cascade,
  name        text not null default '',
  email       text not null default '',
  role        text not null default 'admin',
  created_at  timestamptz not null default now()
);
